# Generated by Django 5.2.4 on 2025-09-17 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='xendit_invoice_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
