# Generated by Django 5.2.4 on 2025-10-09 01:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_payment_expiry_booking_xendit_invoice_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='payment_expiry',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='xendit_invoice_id',
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(choices=[('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('ewallet', 'E-Wallet'), ('bank_transfer', 'Bank Transfer')], default='credit_card', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_gateway',
            field=models.CharField(default='mock_payment_gateway', max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='paid', max_length=20),
        ),
    ]
