# Generated by Django 5.2.4 on 2025-07-12 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, unique=True)),
                ('description', models.TextField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=2000)),
                ('age_rating', models.CharField(choices=[('G', 'General Audience'), ('PG', 'Parental Guidance'), ('R13', 'Restricted 13'), ('R18', 'Restricted 18')], default='PG', max_length=4)),
                ('poster', models.ImageField(blank=True, height_field='poster_height', null=True, upload_to='movie_posters/', width_field='poster_width')),
                ('poster_height', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('poster_width', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('duration', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('release_date', models.DateField()),
                ('language', models.CharField(default='English', max_length=50)),
                ('trailer_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='movies.genre')),
            ],
            options={
                'ordering': ['-release_date', 'title'],
                'indexes': [models.Index(fields=['title'], name='movies_movi_title_652549_idx'), models.Index(fields=['release_date'], name='movies_movi_release_b7ac7d_idx'), models.Index(fields=['is_active'], name='movies_movi_is_acti_00ce83_idx'), models.Index(fields=['is_active', 'release_date'], name='movies_movi_is_acti_39503e_idx')],
            },
        ),
    ]
