# Generated by Django 5.2.4 on 2025-07-12 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(blank=True, height_field='poster_height', null=True, upload_to='movie_posters/', width_field='poster_width'),
        ),
    ]
