# Generated by Django 5.2.4 on 2025-08-27 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0004_alter_movie_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Showtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_date', models.DateField()),
                ('show_time', models.TimeField()),
                ('theater_name', models.CharField(default='Main Theater', max_length=100)),
                ('available_seats', models.PositiveIntegerField(default=100)),
                ('ticket_price', models.DecimalField(decimal_places=2, default=150.0, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showtimes', to='movies.movie')),
            ],
            options={
                'ordering': ['show_date', 'show_time'],
                'indexes': [models.Index(fields=['show_date', 'show_time'], name='showtimes_s_show_da_5f24a9_idx'), models.Index(fields=['movie', 'show_date'], name='showtimes_s_movie_i_4e053a_idx'), models.Index(fields=['is_active'], name='showtimes_s_is_acti_c70ce8_idx')],
                'unique_together': {('movie', 'show_date', 'show_time', 'theater_name')},
            },
        ),
    ]
