# Generated by Django 5.2.4 on 2025-09-08 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_movie_genre'),
        ('showtimes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScreeningRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('capacity', models.PositiveIntegerField(default=100)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='showtime',
            name='showtimes_s_show_da_5f24a9_idx',
        ),
        migrations.RemoveIndex(
            model_name='showtime',
            name='showtimes_s_movie_i_4e053a_idx',
        ),
        migrations.RemoveIndex(
            model_name='showtime',
            name='showtimes_s_is_acti_c70ce8_idx',
        ),
        migrations.AddField(
            model_name='screeningroom',
            name='cinema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='showtimes.cinema'),
        ),
        migrations.AlterUniqueTogether(
            name='showtime',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='showtime',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='showtimes', to='showtimes.screeningroom'),
        ),
        migrations.AlterUniqueTogether(
            name='showtime',
            unique_together={('movie', 'room', 'show_date', 'show_time')},
        ),
        migrations.RemoveField(
            model_name='showtime',
            name='available_seats',
        ),
        migrations.RemoveField(
            model_name='showtime',
            name='theater_name',
        ),
    ]
