# Generated by Django 5.2.4 on 2025-09-16 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showtimes', '0002_cinema_screeningroom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='screeningroom',
            name='seats_per_row',
            field=models.PositiveIntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='showtime',
            name='seats_data',
            field=models.JSONField(default=dict),
        ),
    ]
