# Generated by Django 5.2.4 on 2025-09-16 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showtimes', '0003_screeningroom_seats_per_row_showtime_seats_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinema',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
