# Generated by Django 5.2.4 on 2025-09-16 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showtimes', '0004_alter_cinema_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showtime',
            name='seats_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
